### ISSUE TITLE
Endpoints in Swagger JSON file are being overwritten

### ISSUE THREAD

**Issue by mykeels** [Tiemma/sonic-express#12]
I set this up, and ran my e2e tests, and the JSON file was being generated, but it kept overwriting old endpoints, favoring new ones.

E.g. at some point, there were >5k lines in the JSON file, and by the time the tests ended, there were only 750 lines.

**Comment by tiemma** [comment]
How did you instantiate it? 

Did you put the middle ware in the index file? 

Send some samples of the code please

**Comment by tiemma** [comment]
Closing this issue as I'm yet to get any feedback or debugging information 

Do open at a later time with the information requested.

**Comment by mykeels** [comment]
Hi @Tiemma 

Sorry, I messed up by not responding to this.

Yes, I put the middleware in my app.ts file like:

```ts
app.use(getResponseExpress(app as any, swaggerConfig(__filename), swaggerOutputFilepath));
```

My `swagger-config.ts` looks like:

```ts
const version = process.env.VERSION;
const swaggerDefinition = {
  openapi: '3.0.1',
  info: {
    title: 'Titlel',
    version,
    description:
      Description.'
  },
  servers: [
    {
      url: '/api/v1',
      description: 'Host system path'
    }
  ],
  definitions: {},
  paths: {}
};

export const swaggerOutputFilepath = process.env.SWAGGER_OUTPUT_PATH;

// options for the swagger docs
export const swaggerConfig = (fileName) => ({
  // import swaggerDefinitions
  swaggerDefinition,
  // path to the API docs
  apis: [fileName]
});

```

**Comment by mykeels** [comment]
I was able to get around this, by

- Watching the output swagger file
- At every change in the file, 
  - copy the file to a directory with a unique name
  - deep merge all files in that directory as JSON objects

I'm running automated tests using jest, and I think the process that houses the `setupJest.ts` file is being restarted somehow during the tests, which is causing this behavior, so the above method is a stopgap.
